name: Release Dev

on:
  push:
    branches: [main]

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest

    env:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: us-east-1
      ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Dev image
        uses: QRify-platform/github-actions/docker-build-push@main
        with:
          image-name: qrify-web-dev
