name: Release Dev App

on:
  push:
    branches: [main]

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Dev image
        uses: QRify-platform/github-actions/docker-build-push@main
        with:
          image-name: qrify-web-dev
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
